### ISSUE TITLE
May I port Gridbug from TAC08 to PICO8 and publish to PICO8 BBS?

### ISSUE THREAD

**Issue by sparr** [0xcafed00d/pico-8-games#2]
I played the game and love it, but the current format (requiring building tac08) makes it relatively inaccessible to others. I think it would not be very difficult to rearrange the screen controls to fit on the pico8 screen, and would love to give it a try if that would be ok with you.

**Comment by 0xcafed00d** [comment]
Hi thanks for your interest in my gridbug game. I'm really happy you enjoyed it but its not really finished yet! a version of the game formatted for the pico8 screen already exists in the gridbugx.p8 file. this is the original version and the taco8 version was ported from this. with the original version you can play it with the mouse or joypad/keyboard. i never published the original version as with pico8 i couldnt let the user save their solutions, i tried using the clipboard but found this was awkward and unreliable. I got a bit fed up with the limitations of pico8 so I wrote tac08 so i could have the same api but without the limitations (talk about making it hard for myself!) thinking about it i will release the original on the bbs myself,  so that others can play it. 
out of interest did you finish all the puzzles? if so how long did it take you? one thing it really needs is more  puzzles....

**Comment by sparr** [comment]
I only got a few puzzles in before deciding I wanted to share it with other folks. Notably, on the Zachtronics Discord there is a "games in the genre" channel for all sorts of programming-puzzle games, and also a few other places as well. I look forward to trying to finish the rest of them.

For saving solutions on pico8, have you considered writing the solutions out to the cart file? It's not as nice as what you can do with cartdata, but it would suffice for any individual player who isn't upgrading the cart.

(it's unfortunate your instruction set has 33 instructions; 32 would pack for saving so much more conveniently)

**Comment by 0xcafed00d** [comment]
I did consider saving the levels to the cart, but that would only work if you are running inside pico8 itself and does not work in exported for the web, or exported as a standalone executable.

The reason there are 33 instructions is so it fills the popup box on the original version  along with the run/help/blank icons gives 3x12 rows of icons. 

![gridbugx_000](https://user-images.githubusercontent.com/5556121/74650626-0762d900-517a-11ea-88bd-6e8394618e1d.png)

I would be very interested in your feedback as to the difficulty of the levels, I know that some of the later levels took me many hours to solve, in fact i actually added some extra instructions to make them a bit easier such as swap red/blue but i'm not sure if that makes them easier.
